# Exported from Render on 2025-12-06T18:50:37Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: fullapp-fe
      runtime: static
      repo: https://github.com/foongsy/newapp
      buildCommand: bun run build
      staticPublishPath: dist
      autoDeployTrigger: commit
      rootDir: frontend
      envVars:
      - key: BACKEND_URL
        fromService: 
          type: web
          name: fullapp-be
          envVarKey: RENDER_EXTERNAL_URL
    - type: web
      name: fullapp-be
      runtime: python
      repo: https://github.com/foongsy/newapp
      plan: free
      envVars:
      - key: ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        fromService:
          type: web
          name: fullapp-fe
          envVarKey: RENDER_EXTERNAL_URL
      region: singapore
      buildCommand: uv sync --no-dev
      startCommand: uv run main.py
      healthCheckPath: /health
      autoDeployTrigger: commit
      rootDir: backend